language: groovy
jdk: openjdk7

script:
  - ./grailsw refresh-dependencies
  - ./grailsw test-app -coverage -xml

after_success:
  - ./grailsw coveralls

notifications:
  hipchat:
    rooms:
      - secure: "JiBNbD3lOb8i3Tmf7An2nBGiWSbVRw1Wk7mfNhILmI/1Zxov3QcjdRx53vXuknuOJZaFF73+iDv7xHMdoiax3jDpbN2FrB0Ncju2ROIIFriDe5haF9axIOYU2BHJQ8PD8UVzXHnKCzMxBleBHjLcoTkJGcKYbqcnmgcqOU77Yr4="
