language: groovy
jdk: openjdk7

env:
  global:
  - secure: "SbB1xJZjgC1+ngbe/gRX7PqTQG+wK7IsMahNXLJltr9cqHphyJXe+WAYawGTv2tG0/3FcxOOEWMvUqx8yolu90EpVOQ8njNPGbWmGL+bRwp6srPEsRvSEdqKqUrKeiRTus4DHobbdXj7Aek7ggwOqsQsf57cDSVdMDDvGJjBA0U="
  - secure: "rzSYf025XCw/O4R3F3XPrFX3UyqWZFGHC/J11K/vH0ZlGRZMTWHelrH11SPUoCtU/M+fwQn2j4hhxt6omACPy8lkkHgh2cUSbRurr68+7IRkKpKs7FwioyltNCdRK/ZfUUXn++ZUJU2NjQNdGUA2lic01ZaciSq7Lo3xCfmfc5E="

before_script:
  - npm install -g bower
  - bower install

script:
  - ./grailsw refresh-dependencies
  #- ./grailsw test-app unit:
  - ./grailsw asset-cdn-push -Dgrails.env=deployment --directory=devops-simulator --gzip=true --access-key=$TRAVIS_ACCESS_KEY --secret-key=$TRAVIS_SECRET_KEY
  #- ./grailsw war

#after_success:
#  - ./grailsw aws-eb-deploy -Dgrails.env=production -DBEANSTALK_ACCESS_KEY=$TRAVIS_ACCESS_KEY -DBEANSTALK_SECRET_KEY=$TRAVIS_SECRET_KEY

notifications:
  hipchat:
    rooms:
      "sa+Al0nzzNi+dxpcvwjBt+5dik7G+X2XcXt6BCCEuyYuRiCZEbKq+E/dwcf1tYvTSd6a+b5qRguDG0s3Cdx4AcZBFAmrs9KlELCoFeyOJ45a2ty5TH8s1yofwiWsnoyCiKnG1cppfyCvf5Ebq473k1NvPWxUl/RvQCGaHbuYfto="
